---
- name: Update packages
  dnf:
    name: "*"
    state: latest

- name: Install required packages
  dnf:
    name:
      - java-17-amazon-corretto-devel
      - git
      - docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Add ec2-user to Docker group
  user:
    name: ec2-user
    group: docker
    append: yes

