# jenkins/tasks/configure_plugins.yml
---
- name: Retrieve login info from Secrets Manager
  set_fact:
    login_info: "{{ lookup('aws_secret', 'revlearn/jenkins_login') }}"

- name: Check Jenkins status
  uri:
    url: "{{ base_url }}/api/json"
    method: GET
    return_content: yes
    force_basic_auth: true
    timeout: 5
    user: "{{ login_info.jenkins_username }}"
    password: "{{ login_info.jenkins_pw }}"
  register: jenkins_status
  until: jenkins_status.status == 200
  retries: 3
  delay: 10

- name: Install Jenkins Plugins
  jenkins_plugin:
    url_username: "{{ login_info.jenkins_username }}"
    url_password: "{{ login_info.jenkins_pw }}"
    name: "{{ item }}"
    state: present
  loop: "{{ plugins_to_install }}"

- name: Restart Jenkins & Reload Daemon
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes
  become: true
