tool:
  dockerTool:
    installations:
    - name: "docker"
      properties:
      - installSource:
          installers:
          - fromDocker:
              version: "latest"
  git:
    installations:
    - home: "git"
      name: "Default"
  maven:
    installations:
    - name: "maven"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.9.8"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
  nodejs:
    installations:
    - name: "NodeJS"
      properties:
      - installSource:
          installers:
          - nodeJSInstaller:
              id: "22.6.0"
              npmPackagesRefreshHours: 0
  pipelineMaven:
    daoClass: "org.jenkinsci.plugins.pipeline.maven.dao.PipelineMavenPluginNullDao"
    globalTraceability: false
    triggerDownstreamUponResultAborted: false
    triggerDownstreamUponResultFailure: false
    triggerDownstreamUponResultNotBuilt: false
    triggerDownstreamUponResultSuccess: true
    triggerDownstreamUponResultUnstable: false
  sonarRunnerInstallation:
    installations:
    - name: "sonar-scanner"
      properties:
      - installSource:
          installers:
          - sonarRunnerInstaller:
              id: "6.1.0.4477"
  terraform:
    installations:
    - name: "Terraform"
      properties:
      - installSource:
          installers:
          - terraformInstaller:
              id: "40619-linux-amd64"